name: C build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.7
        with:
          repository: premake/premake-core
          fileName: premake-5.0.0-beta2-linux.tar.gz
          tag: v5.0.0-beta2
      - uses: actions/checkout@v3
      - run: tar xf /home/runner/work/magmatis/magmatis/premake-5.0.0-beta2-linux.tar.gz
      - run: ./premake5 gmake2
      - run: make
