name: C build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: abel0b/setup-premake@v2.2
        with:
         version: 5.0.0-beta2
      - uses: actions/checkout@v3
      - run: premake gmake2
      - run: make
